### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils

### ISSUE THREAD

**Issue by xudaren** [jcasbin/redis-adapter#12]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils
	at org.casbin.adapter.RedisAdapter.addPolicy(RedisAdapter.java:80)
	at org.casbin.jcasbin.main.InternalEnforcer.addPolicy(InternalEnforcer.java:49)
	at org.casbin.jcasbin.main.ManagementEnforcer.addNamedPolicy(ManagementEnforcer.java:327)
	at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:267)
	at org.casbin.jcasbin.main.Enforcer.addPermissionForUser(Enforcer.java:268)

**Comment by hsluoyz** [comment]
@OutOfEastGate

**Comment by OutOfEastGate** [comment]
> Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils at org.casbin.adapter.RedisAdapter.addPolicy(RedisAdapter.java:80) at org.casbin.jcasbin.main.InternalEnforcer.addPolicy(InternalEnforcer.java:49) at org.casbin.jcasbin.main.ManagementEnforcer.addNamedPolicy(ManagementEnforcer.java:327) at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:267) at org.casbin.jcasbin.main.Enforcer.addPermissionForUser(Enforcer.java:268)

@xudaren 
You can add the following dependencies to your project
<dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
            <version>3.2.2</version>
 </dependency>

**Comment by OutOfEastGate** [comment]
> Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils at org.casbin.adapter.RedisAdapter.addPolicy(RedisAdapter.java:80) at org.casbin.jcasbin.main.InternalEnforcer.addPolicy(InternalEnforcer.java:49) at org.casbin.jcasbin.main.ManagementEnforcer.addNamedPolicy(ManagementEnforcer.java:327) at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:267) at org.casbin.jcasbin.main.Enforcer.addPermissionForUser(Enforcer.java:268)

@xudaren 
You can add the following dependencies to your project
`
<dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
            <version>3.2.2</version>
 </dependency>
`

**Comment by OutOfEastGate** [comment]
> Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils at org.casbin.adapter.RedisAdapter.addPolicy(RedisAdapter.java:80) at org.casbin.jcasbin.main.InternalEnforcer.addPolicy(InternalEnforcer.java:49) at org.casbin.jcasbin.main.ManagementEnforcer.addNamedPolicy(ManagementEnforcer.java:327) at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:267) at org.casbin.jcasbin.main.Enforcer.addPermissionForUser(Enforcer.java:268)

@xudaren 
You can add the following dependencies to your project
`
<dependency>

            <groupId>commons-collections</groupId>

            <artifactId>commons-collections</artifactId>

            <version>3.2.2</version>

 </dependency>
`
