### ISSUE TITLE
i want public boolean addPolicies(List<List<String>> rules), please

### ISSUE THREAD

**Issue by xudaren** [jcasbin/redis-adapter#14]
public boolean addPolicies(List<List<String>> rules)

**Comment by xudaren** [comment]
its my fault

**Comment by hsluoyz** [comment]
@xudaren already here:

https://github.com/jcasbin/redis-adapter/blob/686bc3e769459ba1f4f98c4ffa519655450010b3/src/main/java/org/casbin/adapter/RedisAdapter.java#L109-L116

**Comment by xudaren** [comment]
> @xudaren already here:
> 
> https://github.com/jcasbin/redis-adapter/blob/686bc3e769459ba1f4f98c4ffa519655450010b3/src/main/java/org/casbin/adapter/RedisAdapter.java#L109-L116

the performance can be further improved
