### ISSUE TITLE
the performance can be further improved for addPolicies()

### ISSUE THREAD

**Issue by xudaren** [jcasbin/redis-adapter#15]
> @xudaren already here:
> 
> https://github.com/jcasbin/redis-adapter/blob/686bc3e769459ba1f4f98c4ffa519655450010b3/src/main/java/org/casbin/adapter/RedisAdapter.java#L109-L116

the performance can be further improved

_Originally posted by @xudaren in https://github.com/jcasbin/redis-adapter/issues/14#issuecomment-1316164788_

Otherwise, there are too many network interactions

**Comment by xudaren** [comment]
maybe should implement Dispatcher

package org.casbin.jcasbin.persist;

import java.util.List;

public interface Dispatcher {
    void addPolicies(String var1, String var2, List<List<String>> var3);

    void removePolicies(String var1, String var2, List<List<String>> var3);

    void removeFilteredPolicy(String var1, String var2, int var3, String... var4);

    void clearPolicy();

    void updatePolicy(String var1, String var2, List<String> var3, List<String> var4);
}

**Comment by xudaren** [comment]
public class RedisAdapter implements Adapter, BatchAdapter

**Comment by hsluoyz** [comment]
@OutOfEastGate
